### ISSUE TITLE
Arrayable Key By Backed Value

### ISSUE THREAD

**Issue by jjjrmy** [dive-be/php-enum-utils#1]
It would be nice to have an option to flip the array so we are using the PascalCase as the array's value and the backed value as the array's index.

Also maybe an option to use something like Laravel's String Helper to turn the PascaleCase into a [Headline](https://laravel.com/docs/9.x/helpers#method-str-headline)

**Comment by mabdullahsari** [comment]
Hello,

First of all, sorry for the late reply!

You could already achieve the first behaviour using `array_flip` on `toArray` or `array_combine` on `toValues` and `toNames`. The default `toArray` behaviour comes from the very popular package `myclabs/php-enum`.

This package is framework agnostic, and presentation related behaviour should ideally stay in user-land code. I can already see many other similar use-cases and unfortunately cannot include all distinct cases. Thanks for your understanding.
